# Generated by Django 3.0.8 on 2021-07-28 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('downloaded', models.BooleanField()),
                ('Photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamPhotosApp.photos')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamPhotosApp.users')),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamPhotosApp.users'),
        ),
    ]
