# Generated by Django 3.1.5 on 2021-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0004_auto_20210806_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
