# Generated by Django 3.0.8 on 2021-08-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0005_auto_20210806_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
