# Generated by Django 3.1.5 on 2021-08-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0017_creditpurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchases',
            name='paiedamt',
        ),
    ]
