# Generated by Django 3.1.5 on 2021-08-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0018_remove_creditpurchases_paiedamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchases',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
