# Generated by Django 3.1.5 on 2021-08-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0021_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='videopurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('downloaded', models.BooleanField()),
                ('paied', models.FloatField(blank=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamPhotosApp.users')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamPhotosApp.videos')),
            ],
        ),
    ]
