# Generated by Django 3.1.5 on 2021-08-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0022_videopurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='description',
        ),
    ]
