# Generated by Django 3.1.5 on 2021-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0023_auto_20210814_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='category',
            field=models.CharField(blank=True, choices=[('Life', 'category'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='category',
            field=models.CharField(blank=True, choices=[('Life', 'category'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2'), ('City', 'category2')], max_length=255, null=True),
        ),
    ]
