# Generated by Django 3.1.5 on 2021-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0025_auto_20210815_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='format',
            field=models.CharField(blank=True, choices=[('4K (UHD)', '4K (UHD)'), ('2K', '2K'), ('1080p (FHD)', '1080p (FHD)')], max_length=255, null=True),
        ),
    ]
