# Generated by Django 3.1.5 on 2021-08-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0026_videos_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='format',
            field=models.CharField(choices=[('4K (UHD)', '4K (UHD)'), ('2K', '2K'), ('1080p (FHD)', '1080p (FHD)')], max_length=255),
        ),
    ]
