# Generated by Django 3.0.8 on 2021-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0028_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='paypal',
            field=models.EmailField(max_length=254),
        ),
    ]
