# Generated by Django 3.0.8 on 2021-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0029_auto_20210815_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
