# Generated by Django 3.0.8 on 2021-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamPhotosApp', '0030_exchange_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
