# Generated by Django 3.0.8 on 2021-08-17 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PhamPhotosApp', '0032_savedphoto_videophoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videophoto',
            new_name='savedvideo',
        ),
    ]
